### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ghost** [jedypod/generate-dailies#1]
Error: Missing dependencies. Need:
	OpenImageIO
	NumPy
	PyYAML
	Pillow (for mjpeg codec conversion)

but I've installed all packages, brew symlinked. what's wrong?
osx 10.13.6
thx!

**Comment by ghost** [comment]
Package                            Version
---------------------------------- -------
appnope                            0.1.0
backports.shutil-get-terminal-size 1.0.0
Click                              7.0
decorator                          4.4.2
enum34                             1.1.10
ipython                            5.10.0
ipython-genutils                   0.2.0
legofy                             1.0.0
mpmath                             1.1.0
nose                               1.3.7
numpy                              1.16.6
pandas                             0.24.2
pathlib2                           2.3.5
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             6.2.2
pip                                20.1
prompt-toolkit                     1.0.18
ptyprocess                         0.6.0
Pygments                           2.5.2
python-dateutil                    2.8.1
pytz                               2020.1
PyYAML                             5.3.1
scandir                            1.10.0
setuptools                         41.0.1
simplegeneric                      0.8.1
six                                1.14.0
sympy                              1.5.1
traitlets                          4.3.3
wcwidth                            0.1.9
wheel                              0.33.4

**Comment by ghost** [comment]
OpenImageIO 2.1.15

**Comment by devdevaip** [comment]
Can´t run ./daily in Macos BigSur 11.7.8

error that pops-up Missing dependencies 
***************************************
/Users/art/Downloads/generate-dailies-master/pyseq.py:755: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if start is '' or int(start) > frame:
/Users/art/Downloads/generate-dailies-master/pyseq.py:757: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if end is '' or int(end) < frame:
Error: Missing dependencies. Need:
	OpenImageIO
	NumPy
	PyYAML
	Pillow (for mjpeg codec conversion)
Traceback (most recent call last):
  File "/Users/art/Downloads/generate-dailies-master/./daily", line 906, in <module>
    daily = GenerateDaily()
            ^^^^^^^^^^^^^^^
  File "/Users/art/Downloads/generate-dailies-master/./daily", line 104, in __init__
    config = yaml.load(configfile)
             ^^^^
NameError: name 'yaml' is not defined
****************************************

But
Dependencies installed with brew

boost 1.82.0_1
boost-python3 1.82.0
ffmpeg 6.0_1
fmt 10.1.0
freetype 2.13.1
giflib 5.2.1
imath 3.1.9
jpeg-turbo 3.0.0
libheif 1.16.2
libpng 1.6.40
libraw 0.21.1
libtiff 4.5.1
opencolorio 2.2.1
openimageio 2.4.14.0
openexr 3.1.11
pugixml 1.13
pybind11 2.11.1
python@3.11 3.11.4_1
webp 1.3.1
PyYAML-6.0.1

dependencies installed with pip3

Package    Version
---------- -------
numpy      1.24.4
Pillow     10.0.0
pip        23.2.1
PyYAML     6.0.1
setuptools 49.2.1
six        1.15.0
wheel      0.33.1


Any advice will be awesome
cheers

**Comment by jedypod** [comment]
Hm from the traceback it looks like yaml is not importing successfully despite being installed. If you run `/usr/bin/env python3` can you `import yaml` and `yaml.load(configfile)`?

**Comment by devdevaip** [comment]
jedypod:
Sorry for the delay, I hope you are doing well.
I ran /usr/bin/env python3, and can import yaml now, but I had to comment your code and use yaml.safe_load(configfile), 

#config = yaml.load(configfile)
config = yaml.safe_load(configfile)

And your tool is running now with this little change, I am making more tests now to use Ocio too. 
I am using a macOS Big Sur for testing purposes, but I have to use it in a Linux machine. I'll keep you posted.
Thanks a lot. 
Have a great life!

**Comment by devdevaip** [comment]
jerypod:
I can't use ocio.config this error appears in the rendering

generate-dailies-master]# ./daily_copy /Volumes/DE-FS-02/01-PROJECTS/0037-SPACE-HEAT/07-VFX/01-S01-EP01/sc001/sc001-sh0310/01-publish/3D/07-renders/02-lighting/sc001-sh0310-lighting-v07-mParkinson/sc001-sh0310-002-VIK-CHAR-bty.%04d.exr -o ~/tmp/sh0310-002-VIK-test -c avclq --ocio /Volumes/DE-FS-01/02-ASSETS/01-TOOLS/01-3D-tools/OCIO/aces_1.0.3/config.ocio -ct REC.709 -t artist:artist

Error: OCIO color transform /Volumes/DE-FS-01/02-ASSETS/01-TOOLS/01-3D-tools/OCIO/aces_1.0.3/config.ocio does not exist in config. Falling back to default REC.709

It is in yaml config, the path to the ocio.config, it is written in the command line too, and I can not use it also in yamal config

Do you have another example to see what I am doing wrong_
Thank you

**Comment by devdevaip** [comment]
jerypod:
With some trial an error changing the profiles using ACES 1.0.3 ocio.config, I can now use your awesome tool.
Thanks a lot.

**Comment by emlcpfx** [comment]
@devdevaip I'm stuck here as well. I'm using aces 1.2, and getting this error message:

An ImageBuf was destroyed with a pending error message that was never
retrieved via ImageBuf::geterror(). This was the error message:
Could not construct the color transform linear -> REDLog3G10 (no OpenColorIO support)

Any ideas?

**Comment by emlcpfx** [comment]
@devdevaip I think it's because I didn't build OpenImageIO, I just installed the Python bindings. Working on that now. Tough for a newb.

**Comment by devdevaip** [comment]
@emlcpfx which platform are you using? MacOS, Monterey, Ventura or Sonoma, or Linux, which distro?

**Comment by emlcpfx** [comment]
Windows WSL2 Ubuntu 22.04
